<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContenidoMuebles</name>
   <tag></tag>
   <elementGuidId>a9d36ff8-36bb-4790-9c9e-ab5fadedb149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div[4]/div/div/section/div[2]/div/div[2]/div/div[1]/div/div[3]/div/div/div[8]/div[3]/div/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
